# Generated by Django 4.0.6 on 2023-01-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
