# Generated by Django 4.0.6 on 2023-01-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('descriptionn', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('amount', models.FloatField()),
                ('food', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('club', models.BooleanField(default=False)),
                ('swimming', models.BooleanField(default=False)),
                ('games', models.BooleanField(default=False)),
            ],
        ),
    ]
