# Generated by Django 4.0.6 on 2023-01-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_bookedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='booking.book'),
            preserve_default=False,
        ),
    ]
