# Generated by Django 4.0.6 on 2023-01-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_room_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
