# Generated by Django 4.0.6 on 2023-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_room_available_room_room_number_alter_room_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='days',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
