# Generated by Django 4.0.6 on 2023-02-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_room_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookedBy',
            new_name='user',
        ),
    ]
